<a href="https://colab.research.google.com/github/shikhachourey1992/Mateplotlib/blob/main/Churn_customer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

df=pd.read_csv('WA_Fn-UseC_-Telco-Customer-Churn.csv')
print(df.head())


   customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No   
1  5575-GNVDE    Male              0      No         No      34          Yes   
2  3668-QPYBK    Male              0      No         No       2          Yes   
3  7795-CFOCW    Male              0      No         No      45           No   
4  9237-HQITU  Female              0      No         No       2          Yes   

      MultipleLines InternetService OnlineSecurity  ... DeviceProtection  \
0  No phone service             DSL             No  ...               No   
1                No             DSL            Yes  ...              Yes   
2                No             DSL            Yes  ...               No   
3  No phone service             DSL            Yes  ...              Yes   
4                No     Fiber optic             No  ...               No   

  TechSupport StreamingTV StreamingMovies        Contract Pape

In [2]:
print(df['Churn'].value_counts())

Churn
No     5174
Yes    1869
Name: count, dtype: int64


In [3]:
churn=(df['Churn']=='Yes').sum()
print('Churn_Customer',churn)

Churn_Customer 1869


In [4]:
retain_customer=(df['Churn']=='No').sum()
print('Non_Churn_Customer',retain_customer)

Non_Churn_Customer 5174


In [5]:
avg_tenure=df['tenure'].mean()
print('Avarge_tenure',avg_tenure)

Avarge_tenure 32.37114865824223


In [7]:
avg_monthly_charges=df['MonthlyCharges'].mean()
print('Avarge_monthly_charges',avg_monthly_charges)

Avarge_monthly_charges 64.76169246059918


In [10]:
avg_montly_charges_churn=df[df['Churn']=='Yes']['MonthlyCharges'].mean()
print('Avarge_MonthlyCharges',avg_montly_charges_churn)

Avarge_MonthlyCharges 74.44133226324237


In [13]:
avg_monthlycharges_retain=df[df['Churn']=='No']['MonthlyCharges'].mean()
print('Avarage_monthlycharges_retain',avg_monthlycharges_retain)

Avarage_monthlycharges_retain 61.26512369540008


In [18]:
new_coustomer=df[df['tenure']<6]
print(new_coustomer)
print(len(new_coustomer))


      customerID  gender  SeniorCitizen Partner Dependents  tenure  \
0     7590-VHVEG  Female              0     Yes         No       1   
2     3668-QPYBK    Male              0      No         No       2   
4     9237-HQITU  Female              0      No         No       2   
20    8779-QRDMV    Male              1      No         No       1   
22    1066-JKSGK    Male              0      No         No       1   
...          ...     ...            ...     ...        ...     ...   
7016  1471-GIQKQ  Female              0      No         No       1   
7018  1122-JWTJW    Male              0     Yes        Yes       1   
7030  0871-OPBXW  Female              0      No         No       2   
7032  6894-LFHLY    Male              1      No         No       1   
7041  8361-LTMKD    Male              1     Yes         No       4   

     PhoneService     MultipleLines InternetService       OnlineSecurity  ...  \
0              No  No phone service             DSL                   No  ... 

In [19]:
topten=df.sort_values(by='MonthlyCharges',ascending=False)
print(topten.head(10))

      customerID  gender  SeniorCitizen Partner Dependents  tenure  \
4586  7569-NMZYQ  Female              0     Yes        Yes      72   
2115  8984-HPEMB  Female              0      No         No      71   
4804  5734-EJKXG  Female              0      No         No      61   
3894  5989-AXPUC  Female              0     Yes         No      68   
5127  8199-ZLLSA    Male              0      No         No      67   
6118  9924-JPRMC    Male              0      No         No      72   
4610  2889-FPWRM    Male              0     Yes         No      72   
3205  3810-DVDQQ  Female              0     Yes        Yes      72   
6768  9739-JLPQJ  Female              0     Yes        Yes      72   
4875  2302-ANTDP  Female              1     Yes         No      48   

     PhoneService MultipleLines InternetService OnlineSecurity  ...  \
4586          Yes           Yes     Fiber optic            Yes  ...   
2115          Yes           Yes     Fiber optic            Yes  ...   
4804          Ye

In [20]:
def risk(row):
    if row['tenure'] < 6 and row['MonthlyCharges'] > 80:
        return 'High'
    elif row['tenure'] < 12:
        return 'Medium'
    else:
        return 'Low'
df['Risk']=df.apply(risk,axis=1)
print(df[['customerID','Risk']])



      customerID    Risk
0     7590-VHVEG  Medium
1     5575-GNVDE     Low
2     3668-QPYBK  Medium
3     7795-CFOCW     Low
4     9237-HQITU  Medium
...          ...     ...
7038  6840-RESVB     Low
7039  2234-XADUH     Low
7040  4801-JZAZL  Medium
7041  8361-LTMKD  Medium
7042  3186-AJIEK     Low

[7043 rows x 2 columns]


In [21]:
print(df['Risk'].value_counts())

Risk
Low       4974
Medium    1816
High       253
Name: count, dtype: int64


In [22]:
print((df['Churn']=='Yes').sum()/len(df)*(100))

26.536987079369588


In [23]:
print(df['Contract'].value_counts())

Contract
Month-to-month    3875
Two year          1695
One year          1473
Name: count, dtype: int64


In [24]:
print(df.groupby('Contract')['tenure'].mean())

Contract
Month-to-month    18.036645
One year          42.044807
Two year          56.735103
Name: tenure, dtype: float64


In [25]:
summary=df.groupby('Churn').agg({'tenure':'mean','MonthlyCharges':'mean'})
print(summary)

          tenure  MonthlyCharges
Churn                           
No     37.569965       61.265124
Yes    17.979133       74.441332


In [26]:
df.sort_values(by='tenure',ascending=False)
print(df.head(20))

    customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0   7590-VHVEG  Female              0     Yes         No       1           No   
1   5575-GNVDE    Male              0      No         No      34          Yes   
2   3668-QPYBK    Male              0      No         No       2          Yes   
3   7795-CFOCW    Male              0      No         No      45           No   
4   9237-HQITU  Female              0      No         No       2          Yes   
5   9305-CDSKC  Female              0      No         No       8          Yes   
6   1452-KIOVK    Male              0      No        Yes      22          Yes   
7   6713-OKOMC  Female              0      No         No      10           No   
8   7892-POOKP  Female              0     Yes         No      28          Yes   
9   6388-TABGU    Male              0      No        Yes      62          Yes   
10  9763-GRSKD    Male              0     Yes        Yes      13          Yes   
11  7469-LKBCI    Male      

In [27]:
avg_charges=df['MonthlyCharges'].mean()
print(avg_charges)
avg_customer=df['MonthlyCharges']>avg_charges
print(avg_customer)

64.76169246059918
0       False
1       False
2       False
3       False
4        True
        ...  
7038     True
7039     True
7040    False
7041     True
7042     True
Name: MonthlyCharges, Length: 7043, dtype: bool


In [28]:
df[
    (df['tenure']<6) &
    (df['MonthlyCharges']>80)
]

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,Risk
31,4929-XIHVW,Male,1,Yes,No,2,Yes,No,Fiber optic,No,...,No,Yes,Yes,Month-to-month,Yes,Credit card (automatic),95.50,181.65,No,High
47,7760-OYPDY,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,Yes,No,Month-to-month,Yes,Electronic check,80.65,144.15,Yes,High
115,3071-VBYPO,Male,0,Yes,Yes,3,Yes,No,Fiber optic,Yes,...,No,Yes,No,Month-to-month,No,Electronic check,89.85,248.4,No,High
171,1875-QIVME,Female,0,Yes,No,2,Yes,Yes,Fiber optic,No,...,Yes,Yes,Yes,Month-to-month,Yes,Electronic check,104.40,242.8,Yes,High
232,8937-RDTHP,Male,0,No,No,1,Yes,No,Fiber optic,Yes,...,No,No,Yes,Month-to-month,Yes,Mailed check,84.60,84.6,Yes,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6866,0295-PPHDO,Male,0,No,No,1,Yes,Yes,Fiber optic,No,...,No,Yes,Yes,Month-to-month,Yes,Electronic check,95.45,95.45,Yes,High
6888,3191-CSNMG,Female,0,Yes,Yes,3,Yes,No,Fiber optic,No,...,No,Yes,No,Month-to-month,Yes,Electronic check,80.70,239.45,No,High
6889,7952-OBOYL,Male,0,No,No,3,Yes,No,Fiber optic,No,...,Yes,Yes,No,Month-to-month,Yes,Mailed check,89.85,244.45,No,High
6894,1400-MMYXY,Male,1,Yes,No,3,Yes,Yes,Fiber optic,No,...,No,Yes,Yes,Month-to-month,Yes,Electronic check,105.90,334.65,Yes,High


In [29]:
df.to_csv('Clean_dataset.csv',index='False')

In [30]:
# ML Part

# After Pandas analysis:

# 1. Encode categorical columns
# 2. Train-Test Split
# 3. Logistic Regression
# 4. Decision Tree
# 5. Random Forest
# 6. XGBoost
# 7. Accuracy
# 8. Confusion Matrix
# 9. Precision
# 10. Recall
# 11. F1 Score
# 12. Predict new customer churn\

In [31]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix,precision_score,recall_score,f1_score
from xgboost import XGBClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression


In [32]:
df=pd.read_csv('Clean_dataset.csv')
print(df.head())


   Unnamed: 0  customerID  gender  SeniorCitizen Partner Dependents  tenure  \
0           0  7590-VHVEG  Female              0     Yes         No       1   
1           1  5575-GNVDE    Male              0      No         No      34   
2           2  3668-QPYBK    Male              0      No         No       2   
3           3  7795-CFOCW    Male              0      No         No      45   
4           4  9237-HQITU  Female              0      No         No       2   

  PhoneService     MultipleLines InternetService  ... TechSupport StreamingTV  \
0           No  No phone service             DSL  ...          No          No   
1          Yes                No             DSL  ...          No          No   
2          Yes                No             DSL  ...          No          No   
3           No  No phone service             DSL  ...         Yes          No   
4          Yes                No     Fiber optic  ...          No          No   

  StreamingMovies        Contract Pape

In [33]:
print(df.isnull().sum())

Unnamed: 0          0
customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
Risk                0
dtype: int64


In [34]:
df['TotalCharges']=pd.to_numeric(df['TotalCharges'],errors='coerce')
mean_value=df['TotalCharges'].mean()
df['TotalCharges']=df['TotalCharges'].fillna(mean_value)
print(df['TotalCharges'].isnull().sum())



0


In [35]:
le=LabelEncoder()
for col in df.columns:
  if df[col].dtype=='object':
    df[col]=le.fit_transform(df[col])


In [36]:
x=df.drop('Churn',axis=1)
y=df['Churn']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)


In [37]:
lr=LogisticRegression(
    max_iter=5000

)
lr.fit(x_train,y_train)
prediction_lr=lr.predict(x_test)
print(prediction_lr)


[1 0 0 ... 0 0 1]


/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [38]:
ac_s=accuracy_score(y_test,prediction_lr)
print(ac_s)

0.8140525195173882


In [39]:
pre_s=precision_score(y_test,prediction_lr)
print(pre_s)

0.6750788643533123


In [40]:
con_m=confusion_matrix(y_test,prediction_lr)
print(con_m)

[[933 103]
 [159 214]]


In [41]:
d_tree=DecisionTreeClassifier(
    criterion='entropy',
    max_depth=5,
    random_state=42
)
d_tree.fit(x_train,y_train)
prediction_dt=d_tree.predict(x_test)
print(prediction_dt)

[1 0 0 ... 0 0 1]


In [42]:
ac_s=accuracy_score(y_test,prediction_dt)
print(ac_s)

0.7955997161107168


In [44]:
con_m=confusion_matrix(y_test,prediction_dt)
print(con_m)

[[882 154]
 [134 239]]


In [45]:
pre_s=precision_score(y_test,prediction_dt)
print(pre_s)

0.6081424936386769


In [46]:
f1_s=f1_score(y_test,prediction_dt)
print(f1_s)

0.6240208877284595


In [47]:
r_forest=RandomForestClassifier(
    n_estimators=100,
    random_state=42
)
r_forest.fit(x_train,y_train)
prediction_rf=r_forest.predict(x_test)
print(prediction_rf)

[1 0 0 ... 0 0 1]


In [48]:
ac=accuracy_score(y_test,prediction_rf)
print(ac)

0.8055358410220014


In [49]:
pre_s=precision_score(y_test,prediction_rf)
print(pre_s)

0.6826568265682657


In [50]:
con_m=confusion_matrix(y_test,prediction_rf)
print(con_m)

[[950  86]
 [188 185]]


In [51]:
f1_s=f1_score(y_test,prediction_rf)
print(f1_s)

0.5745341614906833


In [52]:
xgb=XGBClassifier(
    n_estimators=100,
    learning_rate=0.1,
    random_state=42,
    max_depth=3
)
xgb.fit(x_train,y_train)
prediction_xgb=xgb.predict(x_test)
print(prediction_xgb)

[1 0 0 ... 0 0 1]


In [53]:
ac=accuracy_score(y_test,prediction_xgb)
print(ac)

0.8119233498935415


In [54]:
pre_s=precision_score(y_test,prediction_xgb)
print(pre_s)

0.6824324324324325


In [55]:
con_m=confusion_matrix(y_test,prediction_xgb)
print(con_m)

[[942  94]
 [171 202]]


In [58]:
f1=f1_score(y_test,prediction_xgb)
print(f1)


0.6038863976083707


In [57]:
ac_lr=accuracy_score(y_test,prediction_lr)
print(ac_lr)
ac_dt=accuracy_score(y_test,prediction_dt)
print(ac_dt)
ac_rf=accuracy_score(y_test,prediction_rf)
print(ac_rf)
ac_xgb=accuracy_score(y_test,prediction_xgb)
print(ac_xgb)

0.8140525195173882
0.7955997161107168
0.8055358410220014
0.8119233498935415


In [60]:
new_customer= [[
    0,#unnamed
    5000,  # customerID

    0,     # gender

    0,     # SeniorCitizen

    1,     # Partner

    0,     # Dependents

    5,     # tenure

    1,     # PhoneService

    0,     # MultipleLines

    2,     # InternetService

    0,     # OnlineSecurity

    0,     # OnlineBackup

    1,     # DeviceProtection

    0,     # TechSupport

    1,     # StreamingTV

    1,     # StreamingMovies

    0,     # Contract

    1,     # PaperlessBilling

    2,     # PaymentMethod

    95.5,  # MonthlyCharges

    450.0 ,# TotalCharges
    0,#Risk



]]

prediction=lr.predict(new_customer)
print(prediction)

[1]


/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


In [62]:
new_customer=[[
  0,#unnamed
    5000,  # customerID

    0,     # gender

    0,     # SeniorCitizen

    1,     # Partner

    0,     # Dependents

    5,     # tenure

    1,     # PhoneService

    0,     # MultipleLines

    2,     # InternetService

    0,     # OnlineSecurity

    0,     # OnlineBackup

    1,     # DeviceProtection

    0,     # TechSupport

    1,     # StreamingTV

    1,     # StreamingMovies

    0,     # Contract

    1,     # PaperlessBilling

    2,     # PaymentMethod

    95.5,  # MonthlyCharges

    450.0 ,# TotalCharges
    0,#Risk
    ]]
prediction=d_tree.predict(new_customer)
print(prediction)

[1]


/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


In [64]:
new_customer=[[
     0,     #unnamed
    5000,  # customerID

    0,     # gender

    0,     # SeniorCitizen

    1,     # Partner

    0,     # Dependents

    5,     # tenure

    1,     # PhoneService

    0,     # MultipleLines

    2,     # InternetService

    0,     # OnlineSecurity

    0,     # OnlineBackup

    1,     # DeviceProtection

    0,     # TechSupport

    1,     # StreamingTV

    1,     # StreamingMovies

    0,     # Contract

    1,     # PaperlessBilling

    2,     # PaymentMethod

    95.5,  # MonthlyCharges

    450.0 ,# TotalCharges
    0,#Risk

]]
prediction=r_forest.predict(new_customer)
print(prediction)

[1]


/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


In [66]:
new_customer=[[
  0,#unnamed
    5000,  # customerID

    0,     # gender

    0,     # SeniorCitizen

    1,     # Partner

    0,     # Dependents

    5,     # tenure

    1,     # PhoneService

    0,     # MultipleLines

    2,     # InternetService

    0,     # OnlineSecurity

    0,     # OnlineBackup

    1,     # DeviceProtection

    0,     # TechSupport

    1,     # StreamingTV

    1,     # StreamingMovies

    0,     # Contract

    1,     # PaperlessBilling

    2,     # PaymentMethod

    95.5,  # MonthlyCharges

    450.0 ,# TotalCharges
    0,#Risk
    ]]
prediction=xgb.predict(new_customer)
print(prediction)

[1]


In [67]:
probabilities=lr.predict_proba(x)[:,1]
df['Churn']=probabilities
def categery(prob):
  if prob > 0.8:
    return 'Highrisk'
  elif prob > 0.5:
    return 'Mediumrisk'
  else:
    return 'Lowrisk'
df['Risk']=df['Churn'].apply(categery)
print(df[['customerID','Risk']])


      customerID        Risk
0           5375  Mediumrisk
1           3962     Lowrisk
2           2564     Lowrisk
3           5535     Lowrisk
4           6511  Mediumrisk
...          ...         ...
7038        4853     Lowrisk
7039        1525     Lowrisk
7040        3367     Lowrisk
7041        5934  Mediumrisk
7042        2226     Lowrisk

[7043 rows x 2 columns]
